import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useGetInvoiceQuery } from "../../../reduxstore/services/InvoicesAPI";

export default function InvoiceView() {
  const statusColors = {
    Unpaid: "bg-yellow-100 text-yellow-800",
    Paid: "bg-green-100 text-green-800",
    Overdue: "bg-red-100 text-red-800",
    "Partially Paid": "bg-blue-100 text-blue-800",
    Cancelled: "bg-gray-100 text-gray-800",
  };
  const formatCurrency = (amount, locale = "en-PK", currency = "PKR") =>
    Number(amount || 0).toLocaleString(locale, { style: "currency", currency });
  const printInvoice = (invRaw) => {
    try {
      const escapeHtml = (str = "") =>
        String(str)
          .replaceAll("&", "&amp;")
          .replaceAll("<", "&lt;")
          .replaceAll(">", "&gt;")
          .replaceAll('"', "&quot;")
          .replaceAll("'", "&#39;");
      const inv = {
        id: invRaw.invoice_no ?? invRaw.id ?? "",
        contractTitle: invRaw.contract_title ?? invRaw.contractTitle ?? "",
        clientName: invRaw.client_name ?? invRaw.clientName ?? "",
        amount: invRaw.total_amount ?? invRaw.amount ?? 0,
        issuedDate: invRaw.issued_date ?? invRaw.issuedDate ?? "",
        dueDate: invRaw.due_date ?? invRaw.dueDate ?? "",
        paymentMethod: invRaw.payment_method ?? invRaw.paymentMethod ?? "",
        status: invRaw.status ?? "Unpaid",
        items: invRaw.items ?? [],
        notes: invRaw.notes ?? "",
      };
      const rows = (inv.items || [])
        .map(
          (it) => `
            <tr>
              <td>${escapeHtml(it.description)}</td>
              <td class="text-right">${formatCurrency(it.amount)}</td>
            </tr>`
        )
        .join("");
      const html = `<!doctype html><html><head><meta charset="utf-8" />
        <style>@page{size:A4;margin:18mm}body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,Helvetica Neue,Arial;color:#111827}.container{max-width:720px;margin:0 auto}.header{display:flex;align-items:center;justify-content:space-between;margin-bottom:24px}.title{font-size:22px;font-weight:700}.badge{display:inline-block;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:600}.badge.Unpaid{background:#FEF3C7;color:#92400E}.badge.Paid{background:#DCFCE7;color:#166534}.badge.Overdue{background:#FEE2E2;color:#991B1B}.badge.Partially{background:#DBEAFE;color:#1E40AF}.badge.Cancelled{background:#F3F4F6;color:#374151}table{width:100%;border-collapse:collapse;margin-top:8px}thead th{text-align:left;font-size:12px;color:#6B7280;text-transform:uppercase;letter-spacing:.04em;padding:10px 12px;border-bottom:1px solid #E5E7EB}tbody td{padding:10px 12px;border-bottom:1px solid #F3F4F6;font-size:14px}.text-right{text-align:right}.total{background:#F9FAFB;font-weight:700}.footer{margin-top:28px;font-size:12px;color:#6B7280;text-align:center}</style></head>
        <body><div class="container">
        <div class="header"><div class="title">Invoice #${escapeHtml(
          inv.id
        )}</div><span class="badge ${escapeHtml(inv.status)}">${escapeHtml(
        inv.status
      )}</span></div>
        <table><thead><tr><th>Description</th><th class="text-right">Amount</th></tr></thead>
        <tbody>${rows}<tr class="total"><td>Total</td><td class="text-right">${formatCurrency(
        inv.amount
      )}</td></tr></tbody></table>
        <div class="footer">Generated by Smart Lawyer • ${new Date()
          .toISOString()
          .slice(0, 10)}</div>
        </div></body></html>`;
      const iframe = document.createElement("iframe");
      Object.assign(iframe.style, {
        position: "fixed",
        right: "0",
        bottom: "0",
        width: "0",
        height: "0",
        border: "0",
      });
      document.body.appendChild(iframe);
      const doc = iframe.contentDocument || iframe.contentWindow?.document;
      if (!doc) throw new Error("Cannot access print document");
      doc.open();
      doc.write(html);
      doc.close();
      setTimeout(() => {
        iframe.contentWindow?.focus();
        iframe.contentWindow?.print();
        setTimeout(() => document.body.removeChild(iframe), 1000);
      }, 250);
    } catch (e) {
      console.error("Failed to print invoice:", e);
    }
  };
  const navigate = useNavigate();
  const { username, id } = useParams();
  const { data: invoice, isFetching, isError } = useGetInvoiceQuery(id);

  if (isFetching) {
    return (
      <div className="rounded-2xl border border-gray-200 bg-white p-3 text-gray-600">
        Loading invoice…
      </div>
    );
  }

  if (isError || !invoice) {
    return (
      <div className="space-y-4">
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-amber-800">
          <div className="flex items-center gap-2 font-medium">
            <i className="ri-alert-line" aria-hidden="true"></i>
            <span>Unable to load invoice details.</span>
          </div>
        </div>
        <button
          onClick={() => navigate(`/admin/${username}/billing`)}
          className="px-4 py-2 text-xs border border-gray-300 bg-white rounded-lg shadow-sm hover:bg-gray-50"
        >
          Back to Billing
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Gradient header */}
      <div className="rounded-2xl border border-emerald-100 bg-gradient-to-r from-emerald-50 to-teal-50 p-3 flex items-center justify-between">
        <h1 className="text-lg font-bold text-emerald-900 flex items-center gap-2">
          <i className="ri-bill-line" aria-hidden="true"></i>
          <span>Invoice #{invoice.id}</span>
        </h1>
        <div className="flex items-center gap-2">
          <button
            onClick={() => printInvoice(invoice)}
            className="px-3 py-1.5 text-xs border border-emerald-600 text-emerald-700 bg-white rounded-lg hover:bg-emerald-50"
          >
            <i className="ri-download-line" aria-hidden="true"></i>{" "}
            <span>PDF</span>
          </button>
          <button
            onClick={() => navigate(`/admin/${username}/billing`)}
            className="px-3 py-1.5 text-xs border border-gray-300 bg-white rounded-lg shadow-sm hover:bg-gray-50"
          >
            <span>Back</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Main card */}
        <div className="lg:col-span-2 space-y-4">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
            <div className="flex items-start justify-between mb-6">
              <div>
                <h2 className="text-xl font-semibold">
                  {invoice.contractTitle || invoice.contract_title}
                </h2>
                <p className="text-gray-500">
                  Billed to: {invoice.clientName || invoice.client_name}
                </p>
              </div>
              <span
                className={`px-3 py-1 rounded-full text-xs font-semibold ${
                  statusColors[invoice.status] || "bg-gray-100 text-gray-600"
                }`}
              >
                {invoice.status}
              </span>
            </div>

            <div className="grid grid-cols-2 gap-6 mb-6">
              <div>
                <h3 className="text-sm font-semibold text-gray-500 mb-1">
                  Issued Date
                </h3>
                <p>{invoice.issuedDate || invoice.issued_date}</p>
              </div>
              <div>
                <h3 className="text-sm font-semibold text-gray-500 mb-1">
                  Due Date
                </h3>
                <p>{invoice.dueDate || invoice.due_date}</p>
              </div>
              <div>
                <h3 className="text-sm font-semibold text-gray-500 mb-1">
                  Payment Method
                </h3>
                <p>{invoice.paymentMethod || invoice.payment_method}</p>
              </div>
              <div>
                <h3 className="text-sm font-semibold text-gray-500 mb-1">
                  Invoice Total
                </h3>
                <p className="font-medium">
                  {formatCurrency(invoice.amount || invoice.total_amount)}
                </p>
              </div>
            </div>

            <div className="mb-6">
              <h3 className="font-semibold mb-2">Invoice Items</h3>
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                      Description
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">
                      Amount
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {invoice.items?.map((item, idx) => (
                    <tr key={`${idx}-${item.description}`}>
                      <td className="px-6 py-3">{item.description}</td>
                      <td className="px-6 py-3 text-right">
                        {formatCurrency(item.amount)}
                      </td>
                    </tr>
                  ))}
                  <tr className="bg-gray-50 font-semibold">
                    <td className="px-6 py-3">Total</td>
                    <td className="px-6 py-3 text-right">
                      {formatCurrency(invoice.amount || invoice.total_amount)}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            {invoice.notes && (
              <div className="mb-2">
                <h3 className="font-semibold mb-2">Notes</h3>
                <p className="text-gray-600">{invoice.notes}</p>
              </div>
            )}
          </div>
        </div>

        {/* Aside */}
        <aside className="space-y-4 lg:sticky lg:top-0 lg:self-start">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm">
            <div className="px-4 py-3 border-b border-gray-100 flex items-center gap-2">
              <i className="ri-information-line text-emerald-600"></i>
              <h3 className="font-semibold">Summary</h3>
            </div>
            <div className="p-4 text-xs text-gray-700 space-y-2">
              <div className="flex items-center gap-2">
                <i className="ri-hashtag text-gray-400"></i>
                <span>
                  Invoice ID: <span className="font-medium">{invoice.id}</span>
                </span>
              </div>
              <div className="flex items-center gap-2">
                <i className="ri-money-dollar-circle-line text-gray-400"></i>
                <span>
                  Total Billed:{" "}
                  <span className="font-medium">
                    {formatCurrency(invoice.amount)}
                  </span>
                </span>
              </div>
              <div className="flex items-center gap-2">
                <i className="ri-timer-line text-gray-400"></i>
                <span>
                  Status: <span className="font-medium">{invoice.status}</span>
                </span>
              </div>
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
