// Staff data for the SmartLawyer.ai application
export const staffData = [
  {
    id: 1,
    name: "Muhammad Fahad Rahman",
    role: "Senior Advocate",
    specialization: "Constitutional Law",
    email: "fahad.rahman@smartlawyer.ai",
    phone: "+92 300 1234567",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    activeCases: 15,
    joinDate: "2019-03-15",
    education: [
      "LLB, Punjab University Law College, 2005",
      "LLM, Harvard Law School, 2007",
    ],
    barAssociations: [
      "Lahore High Court Bar Association",
      "Supreme Court Bar Association",
    ],
    bio: "Muhammad Fahad Rahman has over 15 years of experience practicing constitutional law in Pakistan. He has successfully represented clients before the Supreme Court in several landmark cases.",
    address: "Office #405, Lawyers Complex, Lahore High Court, Lahore",
    accomplishments:
      "Distinguished Service Award, Lahore High Court Bar Association, 2018",
  },
  {
    id: 2,
    name: "Fatima Khalid",
    role: "Advocate",
    specialization: "Family Law",
    email: "fatima.khalid@smartlawyer.ai",
    phone: "+92 311 9876543",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    activeCases: 12,
    joinDate: "2020-06-10",
    education: [
      "LLB, International Islamic University, Islamabad, 2015",
      "LLM (Family Law), University of London, 2017",
    ],
    barAssociations: ["Islamabad Bar Association"],
    bio: "Fatima specializes in family law matters including divorce, custody, and inheritance. She is known for her compassionate approach and thorough case preparation.",
    address: "Suite 15, Lawyers Plaza, F-8 Markaz, Islamabad",
    accomplishments: "Women in Law Excellence Award, 2021",
  },
  {
    id: 3,
    name: "Usman Malik",
    role: "Advocate",
    specialization: "Criminal Law",
    email: "usman.malik@smartlawyer.ai",
    phone: "+92 333 5556677",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    activeCases: 9,
    joinDate: "2021-01-22",
    education: [
      "LLB, University of Karachi, 2016",
      "Criminal Law Certificate, Sindh Judicial Academy, 2017",
    ],
    barAssociations: ["Karachi Bar Association"],
    bio: "Usman is a dedicated criminal defense lawyer with expertise in handling complex criminal cases, including white-collar crimes and financial fraud cases.",
    address: "Office 302, Lawyers' Chambers, City Court, Karachi",
    accomplishments: "Outstanding Criminal Defense Lawyer, Karachi Bar, 2022",
  },
  {
    id: 4,
    name: "Ayesha Iqbal",
    role: "Legal Assistant",
    specialization: "Case Management",
    email: "ayesha.iqbal@smartlawyer.ai",
    phone: "+92 321 1122334",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    activeCases: 20,
    joinDate: "2022-03-05",
    education: ["LLB, Punjab University Law College, 2020"],
    barAssociations: ["Punjab Bar Council (Associate Member)"],
    bio: "Ayesha provides critical support in case preparation, legal research, and client communication. She has strong organizational skills and attention to detail.",
    address: "Office #405, Lawyers Complex, Lahore High Court, Lahore",
    accomplishments: "Employee of the Month, 3 times (2022-2023)",
  },
  {
    id: 5,
    name: "Ali Raza",
    role: "Paralegal",
    specialization: "Document Management",
    email: "ali.raza@smartlawyer.ai",
    phone: "+92 345 9998887",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    activeCases: 18,
    joinDate: "2021-08-15",
    education: [
      "B.A. in Political Science, University of Punjab, 2019",
      "Paralegal Certificate, Pakistan College of Law, 2020",
    ],
    barAssociations: [],
    bio: "Ali handles document preparation, client intake, and administrative support for the firm. He is extremely organized and ensures all legal documents are managed efficiently.",
    address: "Office #405, Lawyers Complex, Lahore High Court, Lahore",
    accomplishments: "Perfect Attendance Award, 2022",
  },
  {
    id: 6,
    name: "Zainab Hassan",
    role: "Office Manager",
    specialization: "Administration",
    email: "zainab.hassan@smartlawyer.ai",
    phone: "+92 333 4445566",
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    activeCases: 0,
    joinDate: "2020-02-10",
    education: ["MBA, Lahore University of Management Sciences, 2018"],
    barAssociations: [],
    bio: "Zainab oversees the firm's administrative operations, including scheduling, billing, HR management, and facility maintenance. She ensures smooth day-to-day operations.",
    address: "Office #405, Lawyers Complex, Lahore High Court, Lahore",
    accomplishments: "Efficiency Innovation Award, 2021",
  },
  {
    id: 7,
    name: "Imran Yasin",
    role: "Senior Advocate",
    specialization: "Commercial Law",
    email: "imran.yasin@smartlawyer.ai",
    phone: "+92 300 7778889",
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    activeCases: 14,
    joinDate: "2018-05-20",
    education: [
      "LLB, University of London, 2008",
      "LLM (Commercial Law), New York University, 2010",
    ],
    barAssociations: [
      "Karachi Bar Association",
      "Sindh High Court Bar Association",
    ],
    bio: "Imran specializes in corporate law, contracts, and international commercial arbitration. He has represented major Pakistani corporations in commercial disputes.",
    address: "Office 201, Business Plaza, I.I. Chundrigar Road, Karachi",
    accomplishments:
      "Commercial Law Expert of the Year, 2020 - Pakistan Legal Awards",
  },
];
